### ISSUE TITLE
Cannot copy the files from one directory to another

### ISSUE THREAD

**Issue by Kickassbadboy** [Kickassbadboy/Python_Projects#1]
Code executes without hitch but does not fullfil the task.

**Comment by dheeraj-rn** [comment]
Should use shutil.copy2 or shutil.copy instead of shutil.copytree . Submitted pull request #2

**Comment by Kickassbadboy** [comment]
Enter the path you want to copy file from/Users/sherlockholmes/Documents/GitHub/Python_Projects/
Enter the destination path/Users/sherlockholmes/Documents/GitHub/
['.DS_Store', 'paswdGenerate.py', 'MoveDir.py', 'dirpath.py', 'README.md', '.git', '.idea']
Traceback (most recent call last):
  File "/Users/sherlockholmes/Documents/GitHub/Python_Projects/MoveDir.py", line 19, in <module>
    shutil.copy2(files,new_path)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 144, in copy2
    copyfile(src, dst)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 21] Is a directory: '.git'

Process finished with exit code 1

**Comment by Kickassbadboy** [comment]
> Enter the path you want to copy file from/Users/sherlockholmes/Documents/GitHub/Python_Projects/
> Enter the destination path/Users/sherlockholmes/Documents/GitHub/
> ['.DS_Store', 'paswdGenerate.py', 'MoveDir.py', 'dirpath.py', 'README.md', '.git', '.idea']
> Traceback (most recent call last):
> File "/Users/sherlockholmes/Documents/GitHub/Python_Projects/MoveDir.py", line 19, in 
> shutil.copy2(files,new_path)
> File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 144, in copy2
> copyfile(src, dst)
> File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 96, in copyfile
> with open(src, 'rb') as fsrc:
> IOError: [Errno 21] Is a directory: '.git'
> 
> Process finished with exit code 1

I tried using copy2 but the problem is its throwing error for files and i want to copy multiple files .

**Comment by Kickassbadboy** [comment]
Closing the issue | Please Reopen if Needed

**Comment by dheeraj-rn** [comment]
This worked for me in Linux. Let me test it on windows

**Comment by Kickassbadboy** [comment]
> This worked for me in Linux. Let me test it on windows

It worked just my code didnt check if there were only files or not !

**Comment by dheeraj-rn** [comment]
> 
> 
> > This worked for me in Linux. Let me test it on windows
> 
> It worked just my code didnt check if there were only files or not !

Ok. What should i do to get that error? 
shutil.copy and shutil.copy2 would only copy files. shutil.copytree would copy the whole folder(folders inside it included), but you wont be able choose(search within directory) which file in that folder you would want to copy.
So would have to use shutil.copy2 recursively to do that.
